version: "3"
services:
  app: 
    build: .
    ports: 
      - "5000:5000"
    depends_on:
       - mongodb

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    command: ["--bind_ip_all"]
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017