version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    command: ["--bind_ip_all"]
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017