version: "3"
services:
  app: 
    build: .
    environment:
      MONGO_URI: mongodb://username:password@host:27017/myapp
    ports: 
      - "5000:5000"
    depends_on:
       - mongo

  mongo:
    image: mongo
    restart: always
    # container_name: mongodb
    command: ["--bind_ip_all"]
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017